### ISSUE TITLE
Ломается верстка после обновления фильтров в UBlock

### ISSUE THREAD

**Issue by maltsev-h** [lesha-dev/asana-ublock#7]
Небольшой фидбек
mozilla firefox, mac 13"

В инбоксе весь верхний хедер ломается :(
<img width="1678" alt="image" src="https://github.com/lesha-dev/asana-ublock/assets/90329073/d63c1c85-1e13-4df9-a467-3e449d02c95b">

В май тасках ломаются кнопки Share, Customize
<img width="1679" alt="image" src="https://github.com/lesha-dev/asana-ublock/assets/90329073/98415982-60d8-4b9c-bb23-e4fbde114932">

В проектах ломается блок с фоловерами, съезжает куда-то влево, из-за чего вкладки проекта колапсятся, и хедер в целом по вертикали увеличивается
<img width="1680" alt="image" src="https://github.com/lesha-dev/asana-ublock/assets/90329073/469a52ad-6284-4e98-ab1a-141dc81032df">

**Comment by maltsev-h** [comment]
C последним коммитом вроде бы получше, но все равно каша в хедерах
<img width="774" alt="image" src="https://github.com/lesha-dev/asana-ublock/assets/90329073/2e04c70b-affd-49cb-b25e-3b601915ad17">
<img width="976" alt="image" src="https://github.com/lesha-dev/asana-ublock/assets/90329073/344546f9-78ba-47c0-8dff-9c75597803a6">

**Comment by lesha-dev** [comment]
Чиню

**Comment by maltsev-h** [comment]
Еще сейчас заметил, что у сабтасков не отображается ссылка на родительскую задачу над названием задачи

**Comment by lesha-dev** [comment]
Все поправил, обнови фильтры и проверяй

**Comment by maltsev-h** [comment]
прости, немного не до этого было... в целом все ок теперь, верстка все еще немного кривая в проектах, но это не критично, хотя бы нет проблем как раньше
<img width="348" alt="image" src="https://github.com/lesha-dev/asana-ublock/assets/90329073/1bb7d902-6f0e-49ea-a854-17ed7ce5d740">

**Comment by lesha-dev** [comment]
Пришли мне сохраненную html без включенных фильтров в телегу? Я посмотрю.

**Comment by lesha-dev** [comment]
Поправил
